### ISSUE TITLE
ロゴのデザイン候補を提案

### ISSUE THREAD

**Issue by taiyaki715** [taiyaki715/seatable#132]
こんな感じがいいんじゃない？とかあればどんどん貼り付けましょう！

**Comment by taiyaki715** [comment]
<img width="231" alt="スクリーンショット 2023-06-01 10 10 15" src="https://github.com/taiyaki715/seatable/assets/124111090/34216c01-a8f2-45b4-a62b-75aecb756a6b">
<img width="272" alt="スクリーンショット 2023-06-01 10 10 49" src="https://github.com/taiyaki715/seatable/assets/124111090/3ef4d01b-d92e-40cb-ae29-f3a330f3abf4">
<img width="343" alt="スクリーンショット 2023-06-01 10 11 06" src="https://github.com/taiyaki715/seatable/assets/124111090/0e64dd37-a96c-4e71-ba8c-db2d60e70a59">

こういう幾何学的なロゴとかどうでしょう？

**Comment by ChizuKobayashi** [comment]
![image](https://github.com/taiyaki715/seatable/assets/126222365/88ae02fd-b89d-4d9d-866c-074ccf6db2dd)
![image](https://github.com/taiyaki715/seatable/assets/126222365/de79258e-fac7-47d5-a0aa-34e31729ac7d)
![image](https://github.com/taiyaki715/seatable/assets/126222365/8d7ff5b7-0202-4394-a03a-1a3b2b53adbc)
![image](https://github.com/taiyaki715/seatable/assets/126222365/c48728a3-7a71-422c-9bd1-4a01d012d37f)
![image](https://github.com/taiyaki715/seatable/assets/126222365/26b01ec0-5309-4aba-b1df-043b4ad6c852)

図？の下にseatableを書く感じがいいかも

**Comment by ChizuKobayashi** [comment]
https://logostock.jp/logo-knowledge/

**Comment by ChizuKobayashi** [comment]
＜メモ＞
・誰に届けるのか
→seatableを使用する人
・目的
→seatableを使っていることがロゴを見ただけですぐに理解できるようにする
・モチーフ
→椅子やソファなどの座席
・どんなイメージ？
→スマートで分かりやすいイメージ
・色
→トンマナ参照。寒色系？

**Comment by taiyaki715** [comment]
@ChizuKobayashi 
SmartHRのロゴとかいいかもね

**Comment by ri0410** [comment]
![Image](https://github.com/taiyaki715/seatable/assets/93765509/40130b29-891e-4c4a-bf66-66f92b2a8c27)


![Image](https://github.com/taiyaki715/seatable/assets/93765509/4b141e83-b079-4070-9232-fe8537fe5ec8)

ロゴの文字部分の色全部同じじゃなくて一部変えてるデザインいいな〜と思ったので載せます！

**Comment by ChizuKobayashi** [comment]
なんこかデザイン考えてみました～
好きなのとか、もっとこんなデザインはどう？とか、このデザインのここを修正すると良いかもとか
意見くださ～い
seatableの文字はえびちゃんが案出してくれた、一部色変えしたいと思ってます！
![image](https://github.com/taiyaki715/seatable/assets/126222365/5a547b5f-2ffb-4df6-98b8-912c13e66a01)

**Comment by ChizuKobayashi** [comment]
あんまスタイリッシュなの思いつかなかった。。。

**Comment by taiyaki715** [comment]
2, 3, 5いいと思う！
5とかは特に「繋がり」っぽいイメージがあって好みです〜
